export const follow = [
  "FOLLOW ME AND I WILL FOLLOW YOU BACK 100%👈",
  "FOLLOW ME AND I WILL FOLLOW YOU BACK 100%👈👈",
  "FOLLOW ME AND I WILL FOLLOW YOU BACK 100%👈👈👈",
  "FOLLOW ME AND I WILL FOLLOW YOU BACK 100%👈👈👈👈",
  "FOLLOW ME AND I WILL FOLLOW YOU BACK 100%👈👈👈👈👈👈👈"
]