export const grow = [
  "GROWGROWGROWGROWGROW",
  "GROWGROWGROWGROWGROWGROWGROW",
  "GROWGROWGROWGROWGROWGROWGROWGROW",
  "GROWGROW",
  "GROWGROWGROW",
  "GROW",
  "GROWGROWGROWGROW",
  "GROWGROWGROWGROWGROWGROW",
  "GROWGROWGROWGROWGROWGROWGROWGROWGROWGROW",
  "GROWGROWGROWGROWGROWGROWGROWGROWGROWGROWGROW",
  "GROWGROWGROWGROWGROWGROWGROWGROWGROWGROWGROWGROW",
  "GROWGROWGROWGROWGROWGROWGROWGROWGROWGROWGROWGROWGROW",
  "GROWGROWGROWGROWGROWGROWGROWGROWGROWGROWGROWGROWGROWGROW",
  "GROWGROWGROWGROWGROWGROWGROWGROWGROWGROWGROWGROWGROWGROWGROW"
]